### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable in Pingen.php:607

### ISSUE THREAD

**Issue by marin246** [pingencom/pingen#10]
Hi,

PHP 7.2 changed the way count() behaves: [RFC](https://wiki.php.net/rfc/counting_non_countables)
 Please update the code such that no warning is thrown anymore.

Thanks in advance!

**Comment by pingencom** [comment]
Fixed with new release 1.2.3
https://github.com/pingencom/pingen/releases/tag/1.2.3
