### ISSUE TITLE
document_send() does not take account default address position anymore

### ISSUE THREAD

**Issue by marin246** [pingencom/pingen#14]
starting from 1.2.6, document_send() defaults to address left (rightaddress => 0) and not to the account default as stated in the API docs.
Change behavior back if possible

**Comment by pingencom** [comment]
It is true that 1.2.6 has changed the default behaviour when using the class. Lower versions were not passing 'rightaddress' parameter at all (what defaulted to the account setting), now the class is sending the parameter.

To make it work again, you have to explicitly set the rightaddress parameter to NULL when calling the appropriate method.

However i think we have a different mistake in the api documentation: document_send leads to /document/send/id/xxxx this endpoint only sends an existing document (that already has the information if the address location is left or right) and it seems this parameter does not really exist in the API.

Can you confirm that you were actually using document_upload(), and not document_send() ?

**Comment by marin246** [comment]
I was using document_upload() with `$iSend == false`. And afterwards document_send() to send the document.

It works when explicitly specifying $iAddress == true. When using this PHP library, by default the Address is assumed to be on the left. This is not as described in the Pingen API docs, where it says that the Account default is used.
Maybe add somewhere a notice that the PHP Library implementations is different from the API docs.
