### ISSUE TITLE
Add this library to Packagist

### ISSUE THREAD

**Issue by sprain** [pingencom/pingen#3]
https://packagist.org

Composer users will be grateful :)

**Comment by onlime** [comment]
Nobody else did, so I have added it to Packagist on 2015-11-17.
https://packagist.org/packages/pingencom/pingen

**Comment by pingencom** [comment]
@onlime We have just sent you an E-Mail to reclaim the packagist entry, as we will be actively maintaining this repo again (sorry for the absence...)

**Comment by onlime** [comment]
@pingencom done. I've transferred Packagist package ownership to you guys. Thanks for actively maintaining this again. Happy developing!
